IOS-685: Adding credit cards' validation.
netguru/ngrvalidator pull request #15
Opened 2017-03-01 14:40 UTC by pbruz

Adding credit cards' validation.

2017-03-01 15:30 UTC, akashivskyy requested changes

2017-03-01 15:30 UTC, akashivskyy commented on NGRValidator/NGRValidator/Categories/NSString+NGRValidator.m
> +- (BOOL)fulfillsLuhnAlgorithm {
This method being private doesn't make it unsusceptible to collisions. It should be prefixed by `ngr_`, like others.

2017-03-01 15:30 UTC, akashivskyy commented on NGRValidator/NGRValidator/Categories/NSString+NGRValidator.m
> +    NSString *number = [self stringByReplacingOccurrencesOfString:@" " withString:@""];
I suggest that you also do:

```objc
[... stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]
```

2017-03-01 15:35 UTC, pbruz commented on NGRValidator/NGRValidator/Categories/NSString+NGRValidator.m
> +- (BOOL)fulfillsLuhnAlgorithm {
True that 👍

2017-03-02 09:46 UTC, akashivskyy requested changes

2017-03-02 09:46 UTC, akashivskyy commented on NGRValidator/NGRValidator/Categories/NSString+NGRValidator.m
>  - (BOOL)evaluatePattern:(NSString *)pattern {
Can you also add prefixes to the other methods by the way? :)

2017-03-02 09:50 UTC, akashivskyy approved these changes
🚢 ✨

2017-03-02 12:32 UTC, merged