[WIP] [IOS-679]: Research amount of work to remove nsobject inheritance
netguru/ngrvalidator pull request #26
Opened 2017-03-29 16:28 UTC by kkapitan

### Ticket

https://netguru.atlassian.net/browse/IOS-679

### Description

This PR introduces few tweaks for Swift 3.0 support as a side effect of this research. Now NGRValidator is capable of validating swift structs and classes without NSObject inheritance.  

(However it struggles a bit with optionals)

2017-03-30 16:57 UTC, rad3ks requested changes
Big plus for test cases

2017-03-30 16:57 UTC, rad3ks commented on NGRValidator/NGRValidator/NGRRuntime.swift
> +        let supportedDisplayStyles: [Mirror.DisplayStyle] = [.struct, .class]
can be `static`, correct?

2017-03-30 16:57 UTC, rad3ks commented on NGRValidator/NGRValidator/NGRRuntime.swift
> +        return mirror.displayStyle.map { supportedDisplayStyles.contains($0) } ?? false
I would implement it more precisely:
```
switch mirror.displayStyle {
case .struct: 
    fallthrough
case .class: 
    return true
default: 
    return false
}
```
What do you think?

2017-03-30 16:57 UTC, rad3ks commented on NGRValidator/NGRValidator/NGRRuntime.swift
> +        let childProperties = children.flatMap({ $0.label })
Could be just `children.flatMap { $0.label }` without parenthesis

2017-03-30 16:57 UTC, rad3ks commented on NGRValidator/NGRValidator/NGRValidator+Swift.swift
> +            print("Lack of validation rules in \(model) model. Validation couldn't be processed.")
`print` should be removed

2017-03-30 16:57 UTC, rad3ks commented on NGRValidator/NGRValidator/NGRValidator+Swift.swift
> +                print("Property named '\(validator.property)' wasn't found in \(model) model. Property validation skipped.")
`print` should be removed

2017-03-30 16:57 UTC, rad3ks commented on NGRValidator/NGRValidator/NGRValidator+Swift.swift
> +                continue
Well, this means the `guard` statement is not needed, is it?

2017-03-31 09:31 UTC, kkapitan commented on NGRValidator/NGRValidator/NGRRuntime.swift
> +        return mirror.displayStyle.map { supportedDisplayStyles.contains($0) } ?? false
Yeah that's better, thanks :)  I've slightly modified your solution because displayStyle is an optional.

2017-03-31 09:32 UTC, kkapitan commented on NGRValidator/NGRValidator/NGRRuntime.swift
> +        let childProperties = children.flatMap({ $0.label })
👍

2017-03-31 09:38 UTC, kkapitan commented on NGRValidator/NGRValidator/NGRValidator+Swift.swift
> +                print("Property named '\(validator.property)' wasn't found in \(model) model. Property validation skipped.")
Yeah I didn't like it either but i wanted to remain consistent with the objective-c counterpart like [here](https://github.com/netguru/ngrvalidator/blob/develop/NGRValidator/NGRValidator/NGRValidator.m#L81). I think the design choice here was to warn the client about some validation issues that are non-fatal for the overall execution.

2017-03-31 09:43 UTC, kkapitan commented on NGRValidator/NGRValidator/NGRValidator+Swift.swift
> +                continue
If I understand correctly -  removing this print here allows us to put the condition in `guard` as a part of `for` loop using `where` keyword. But then again in the comment above I've explained why I've left the prints. So I chose to use `guard` +  `continue` to exit current iteration if the `guard` condition is not met.

2017-03-31 12:24 UTC, rad3ks commented on NGRValidator/NGRValidator/NGRValidator+Swift.swift
> +                print("Property named '\(validator.property)' wasn't found in \(model) model. Property validation skipped.")
Well ok, so let's leave it like that for now

2017-03-31 12:25 UTC, rad3ks commented on NGRValidator/NGRValidator/NGRValidator+Swift.swift
> +                continue
Oh ok, I misunderstood that

2017-03-31 12:25 UTC, rad3ks approved these changes

2017-03-31 12:49 UTC, merged